### ISSUE TITLE
Implementar panel de acciones en trayicon

### ISSUE THREAD

**Issue by OscarDevCPP** [puyu-pe/puka#16]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Al hacer click en el trayicon se debe habrir un panel donde el usuario podra volver a imprimir los tickets que quedaron en cola de impresión.

* El nuevo panel de acciones tiene que ser el componente padre del trayicon

**Comment by OscarDevCPP** [comment]
Diseño de primera pestaña implementada:


![Image](https://github.com/puyu-pe/puka/assets/143469741/950a3c39-fdda-4acf-b066-878d1268ed48)




Diseño de segunda pestaña implementada:


![Image](https://github.com/puyu-pe/puka/assets/143469741/f065badc-c63f-426b-9174-dc9179d48b8b)

**Comment by velnae** [comment]
funcionalidad de edicion de logo, ya no va
agregar test de impresion
